export const DATA_LOADED = "DATA_LOADED";
export const VALIDATE_NAME = "VALIDATE_NAME";
export const USER_LOGOUT = "USER_LOGOUT";
export const CHOOSE_COLOR = "CHOOSE_COLOR";
export const LOADING_POSTS = "LOADING_POSTS";